blank_issues_enabled: false
contact_links:
  - name: Feature Requests & Questions
    url: https://github.com/tannerlinsley/react-query/discussions
    about: Please ask and answer questions here.
  - name: Community Chat
    url: https://discord.gg/mQd7egN
    about: A dedicated discord server hosted by Tanner Linsley
